import { FaAws } from "react-icons/fa6";
import {
  SiAnsible,
  SiArgo,
  SiDocker,
  SiGithub,
  SiGrafana,
  SiJenkins,
  SiKubernetes,
  SiLinux,
  SiNginx,
  SiPostgresql,
  SiPrometheus,
  SiTerraform,
} from "react-icons/si";

export const toolCatalog = [
  {
    id: "linux",
    name: "Linux Host",
    shortLabel: "Linux",
    category: "Compute",
    icon: SiLinux,
    color: "#f5be04",
    accent: "#fde68a",
    description: "Base operating system for workloads, agents, and automation.",
  },
  {
    id: "docker",
    name: "Docker",
    shortLabel: "Docker",
    category: "Containers",
    icon: SiDocker,
    color: "#2496ed",
    accent: "#7dd3fc",
    description: "Container packaging and runtime layer.",
  },
  {
    id: "kubernetes",
    name: "Kubernetes",
    shortLabel: "K8s",
    category: "Orchestration",
    icon: SiKubernetes,
    color: "#326ce5",
    accent: "#93c5fd",
    description: "Cluster scheduler, services, ingress, and scaling.",
  },
  {
    id: "terraform",
    name: "Terraform",
    shortLabel: "Terraform",
    category: "IaC",
    icon: SiTerraform,
    color: "#844fba",
    accent: "#c4b5fd",
    description: "Infrastructure provisioning and environment management.",
  },
  {
    id: "aws",
    name: "AWS",
    shortLabel: "AWS",
    category: "Cloud",
    icon: FaAws,
    color: "#ff9900",
    accent: "#fdba74",
    description: "Cloud platform for networking, compute, and managed services.",
  },
  {
    id: "jenkins",
    name: "Jenkins",
    shortLabel: "Jenkins",
    category: "CI/CD",
    icon: SiJenkins,
    color: "#d24939",
    accent: "#fca5a5",
    description: "Pipeline execution and deployment automation.",
  },
  {
    id: "github-actions",
    name: "GitHub",
    shortLabel: "GitHub",
    category: "Source",
    icon: SiGithub,
    color: "#111827",
    accent: "#cbd5e1",
    description: "Source control, pull requests, and workflow triggers.",
  },
  {
    id: "argocd",
    name: "Argo CD",
    shortLabel: "Argo CD",
    category: "GitOps",
    icon: SiArgo,
    color: "#ef7b4d",
    accent: "#fdba74",
    description: "Declarative delivery for Kubernetes environments.",
  },
  {
    id: "ansible",
    name: "Ansible",
    shortLabel: "Ansible",
    category: "Automation",
    icon: SiAnsible,
    color: "#ee0000",
    accent: "#fda4af",
    description: "Configuration and server orchestration.",
  },
  {
    id: "prometheus",
    name: "Prometheus",
    shortLabel: "Prometheus",
    category: "Observability",
    icon: SiPrometheus,
    color: "#e6522c",
    accent: "#fdba74",
    description: "Metrics collection and alert evaluation.",
  },
  {
    id: "grafana",
    name: "Grafana",
    shortLabel: "Grafana",
    category: "Observability",
    icon: SiGrafana,
    color: "#f46800",
    accent: "#fb923c",
    description: "Dashboards and operational visibility.",
  },
  {
    id: "postgresql",
    name: "PostgreSQL",
    shortLabel: "Postgres",
    category: "Data",
    icon: SiPostgresql,
    color: "#336791",
    accent: "#93c5fd",
    description: "Application database and durable storage layer.",
  },
  {
    id: "nginx",
    name: "Nginx",
    shortLabel: "Nginx",
    category: "Edge",
    icon: SiNginx,
    color: "#009639",
    accent: "#86efac",
    description: "Ingress, reverse proxy, and load balancing edge.",
  },
];

export const toolCatalogMap = Object.fromEntries(toolCatalog.map((tool) => [tool.id, tool]));

export const starterNodes = [
  { id: "node-1", toolId: "github-actions", label: "Application Source", x: 46, y: 94 },
  { id: "node-2", toolId: "jenkins", label: "Build Pipeline", x: 266, y: 94 },
  { id: "node-3", toolId: "docker", label: "Container Image", x: 486, y: 94 },
  { id: "node-4", toolId: "argocd", label: "GitOps Deploy", x: 706, y: 94 },
  { id: "node-5", toolId: "kubernetes", label: "Production Cluster", x: 706, y: 254 },
  { id: "node-6", toolId: "prometheus", label: "Metrics", x: 266, y: 254 },
  { id: "node-7", toolId: "grafana", label: "Dashboards", x: 486, y: 254 },
  { id: "node-8", toolId: "postgresql", label: "Primary Database", x: 706, y: 414 },
];

export const starterEdges = [
  { id: "edge-1", from: "node-1", to: "node-2" },
  { id: "edge-2", from: "node-2", to: "node-3" },
  { id: "edge-3", from: "node-3", to: "node-4" },
  { id: "edge-4", from: "node-4", to: "node-5" },
  { id: "edge-5", from: "node-5", to: "node-8" },
  { id: "edge-6", from: "node-5", to: "node-6" },
  { id: "edge-7", from: "node-6", to: "node-7" },
];
